# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rescuespot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RescueSpot',
            new_name='RescueSpots',
        ),
    ]
