# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181025_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescueSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.CharField(default='This message was auto-generated by the App', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='RescueSpots',
        ),
    ]
