# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_rescues'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcesAvail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.TextField()),
                ('qty', models.IntegerField()),
                ('unit', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Resources',
            new_name='ResourcesNeed',
        ),
        migrations.AddField(
            model_name='camps',
            name='currentPeople',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
