"""
Definition of models.
"""

from django.db import models

# Create your models here.

class Camps(models.Model):
	name = models.TextField()
	capacity = models.IntegerField()
	currentPeople = models.IntegerField()
	contact = models.IntegerField()
	lat = models.DecimalField(max_digits=9, decimal_places=6) 
	lon = models.DecimalField(max_digits=9, decimal_places=6)

	def __str__(self):
		return self.name

class ResourcesNeed(models.Model):
	cid = models.ForeignKey(Camps, on_delete = models.CASCADE)
	resource = models.TextField()
	qty = models.IntegerField()
	unit = models.TextField()

class ResourcesAvail(models.Model):
	cid = models.ForeignKey(Camps, on_delete = models.CASCADE)
	resource = models.TextField()
	qty = models.IntegerField()
	unit = models.TextField()

class ResourcesNew(models.Model):
	resource = models.TextField()
	qty = models.IntegerField()
	unit = models.TextField()

class RescueSpot(models.Model):
    lat = models.DecimalField(max_digits=9, decimal_places=6)
    lon = models.DecimalField(max_digits=9, decimal_places=6)
    description = models.CharField(default="This message was auto-generated by the App", max_length=500)

class ForecastPlace(models.Model):
    name = models.CharField(max_length=500)
    lat = models.DecimalField(max_digits=9, decimal_places=6)
    lon = models.DecimalField(max_digits=9, decimal_places=6)